version: "3"
services:
  app:
    container_name: tpApp
    build: ./mainServer
    restart: always
    ports:
      - "7777:7777"
    networks:
      - tpnet

  data_server:
    container_name: tp_data_server
    build: ./apiServer
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27018/tp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - tpnet

  mongodb:
    container_name: tp-mongodb
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - tpData:/data/db
    networks:
      - tpnet

  auth_server:
    container_name: tp_auth_server
    build: ./authServer
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27018/authEW_TP
    ports:
      - "7778:7778"
    depends_on:
      - mongodb
    networks:
      - tpnet
      
networks:
  tpnet:
    name: tpnet
    driver: bridge
volumes:
  tpData:
  