# Data : 30-3-2023
# Este programa serve para retirar quais os campos que existem nos ficheiros de dados fornecidos no dataset
import json
def nowAllKeys(data):
    listaResultado = []
    listaResultado += data[0].keys()
    return listaResultado

def main ():
    listaResultado = []
    f1 = open('data/atco1_acordaos.json')
    data1 = json.load(f1)
    listaResultado += nowAllKeys(data1)
    f1.close()
    print("Tudo nice 1...")
    f2 = open('data/jcon_acordaos.json')
    data2 = json.load(f2)
    listaResultado += nowAllKeys(data2)
    f2.close()
    print("Tudo nice 2...")
    f3 = open('data/jdgpj_acordaos.json')
    data3 = json.load(f3)
    listaResultado += nowAllKeys(data3)
    f3.close()
    print("Tudo nice 3...")
    f4 = open('data/jsta_acordaos.json')
    data4 = json.load(f4)
    listaResultado += nowAllKeys(data4)
    f4.close()
    print("Tudo nice 4...")
    f5 = open('data/jstj_acordaos.json')
    data5 = json.load(f5)
    listaResultado += nowAllKeys(data5)
    f5.close()
    print("Tudo nice 5...")
    f6 = open('data/jtca_acordaos.json')
    data6 = json.load(f6)
    listaResultado += nowAllKeys(data6)
    f6.close()
    print("Tudo nice 6...")
    f7 = open('data/jtcampca_acordaos.json')
    data7 = json.load(f7)
    listaResultado += nowAllKeys(data7)
    f7.close()
    print("Tudo nice 7...")
    f8 = open('data/jtcampct_acordaos.json')
    data8 = json.load(f8)
    listaResultado += nowAllKeys(data8)
    f8.close()
    print("Tudo nice 8...")
    f9 = open('data/jtre_acordaos.json')
    data9 = json.load(f9)
    listaResultado += nowAllKeys(data9)
    f9.close()
    print("Tudo nice 9...")
    f10 = open('data/jtrg_acordaos.json')
    data10 = json.load(f10)
    listaResultado += nowAllKeys(data10)
    f10.close()
    print("Tudo nice 10...")
    f11 = open('data/jtrl_acordaos.json')
    data11 = json.load(f11)
    listaResultado += nowAllKeys(data11)
    f11.close()
    print("Tudo nice 11...")
    f12 = open('data/jtrp_acordaos.json')
    data12 = json.load(f12)
    listaResultado += nowAllKeys(data12)
    f12.close()
    print("Tudo nice 12...")
    f13 = open('data/jtcn_acordaos.json')
    data13 = json.load(f13)
    listaResultado += nowAllKeys(data13)
    f13.close()
    print("Tudo nice 13...")
    f14 = open('data/jtrc_acordaos.json')
    data14 = json.load(f14)
    listaResultado += nowAllKeys(data14)
    f14.close()
    print("Tudo nice 14...")

    print(listaResultado)

if __name__ == "__main__":
    main()

