var mongoose = require ('mongoose')
var processoSchema= new mongoose.Schema({
    _id:String,
    /*Do ficheiro data/atco1_acordaos.json*/ 
    "Nº Convencional":String,
    "Acordão": String,
    Processo: String,
    Relator: String,
    Descritores: [String],
    "Nº do Documento": String,
    "Data do Acordão": String,
    "Espécie": String,
    Requerente: String,
    Requerido: String,
    "Votação": String,
    Privacidade: String,
    "Normas Apreciadas":String,
    "Normas Julgadas Inconst.": String,
    "Área Temática 1": String,
    "Área Temática 2": String,
    "Decisão": String,
    "Sumário": String,
    "Texto Integral": String,
    url: String,
    tribunal: String,
    "Volume dos Acordãos do T.C.": String,
    "Constituição": String,
    "Legislação Nacional": String,
    "Nº do Diário da República": String,
    "Série do Diário da República": String,
    "Data do Diário da República": String,
    "Página do Diário da República": String,
    "Nº do Boletim do M.J.": String,
    "Página do Boletim do M.J.": String,
    "Jurisprudência Constitucional": String,
    "Normas Suscitadas": String,
    "Declaração de Voto": String,
    "Voto Vencido": String,
    "Indicações Eventuais": String,
    "Normas Declaradas Inconst.": String,
    "Página do Volume": String,
    "Outras Publicações": String,
    "Legislação Comunitária": String,
    "Referência a Pareceres": String,
    "Referências Internacionais":String,
    "Outra Jurisprudência": String,
    "Jurisprudência Internacional":String,
    "Jurisprudência Estrangeira":String,
    "Legislação Estrangeira":String,
    /*Do ficheiro data/jcon_acordaos.json*/ 
    "Recorrido 1": String,
    "Recorrido 2": String,
    Recorrente: String,
    Tribunal: String,
    "Data de Entrada": String,
    "Meio Processual": String,
    "Objecto":String,
    "Referência a Doutrina": String,
    "Jurisprudência Nacional":String,
    "Nº do Volume": String,
    "Recusa Aplicação": String,
    "Ano da Publicação": String,
    "Apêndice": String,
    "Data do Apêndice": String,
    "1ª Pág. de Publicação do Acordão":String,
    "Referência Publicação 1":String,
    /* Do ficheiro jdgpj_acordaos.json*/
    "Tribunal 1ª instância": String,
    "Juízo ou Secção": String,
    "Tipo de Ação":String,
    "Tipo de Contrato":String,
    "Autor": String,
    "Réu": String,
    "Data da Decisão": String,
    "Texto das Cláusulas Abusivas": String,
    Recursos: String,
    "Data do Acórdão": String,

    
})

module.exports = mongoose.model('process',processoSchema)